= Docker stuff

== Installation

.get.docker.com
----
curl -fsSL get.docker.com -o get-docker.sh | sh
----

WARNING: could be dangerous if get.docker.com was hacked or network failed during transfer ...

.CentOS
----
./install-docker-centos.sh
----

== Docker Toolbox

TIP: It's time to use Docker Desktop (https://www.docker.com/products/docker-desktop)

I'm using Docker Toolbox (https://www.docker.com/products/docker-toolbox)

----
docker-machine create --driver virtualbox default
docker-machine ls

docker-machine start default
docker-machine env default

docker-machine ip
docker-machine ssh
----

SCP/FTP/SFTP : `docker/tcuser`

== Docker Compose

Check configuration

 $ docker-compose config
 
(Force) rebuild

 $ docker-compose up -d
 $ docker-compose up -d --build

Check process

 $ docker-compose ps

== Docker commands

https://docs.docker.com/engine/reference/commandline/cli/

[%header,cols="3, 1"]
|===
| Command
| Description

| `docker container ls`
| list containers

| `docker container ls -a --format 'table {{.ID}}\t{{.Image}}\t{{.Names}}\t{{.Status}}'`
| list containers

| `docker ps -a`
| to be deprecated

| `docker container logs -f [container_name]`
| show log

| `docker exec -it [container_name] bash`
| execute command

| `docker image ls`
| list images

| `docker images`
| list images (to be deprecated)

| `docker image prune -f`
| clean images

| `docker rmi $(docker images --quiet --filter "dangling=true")`
| clean images

| `docker volumes ls`
| list docker volumes

| `docker system prune [--volumes]`
| clean stopped container

| `docker container prune -f`
| clean stopped container

| `docker rm $(docker ps -a --format '{{.ID}}' --filter 'exited=0')`
| clean stopped container

| `docker stats`
| resources usage
|===

 docker container ls -q | xargs docker stats

 $ docker-machine ssh
 $ docker@default:~$ sudo -i
 $ ls -l /mnt/sda1/var/lib/docker/volumes/

== Dockerfile tips

=== Docker daemon configuration

==== Default Log Driver

./etc/docker/daemon.json
[source,json]
----
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10000k",
    "max-file": "10"
  }
}
----

==== Insecure Registries

./etc/docker/daemon.json
[source,json]
----
{
  "insecure-registries" : [
    "my.registry.com",
    "dummy.registry.com"
  ]
}
----

=== Docker push to private registry

----
docker login -u=USER -p=PASSWORD http://my-private-registry[:port]
docker image build -t my-private-registry[:port]/NAMESPACE/IMAGE:TAG .
docker image push my-private-registry[:port]/NAMESPACE/IMAGE:TAG
docker logout
----

=== Non root user

----
RUN groupadd -r myuser
RUN useradd -m -r -g myuser myuser
USER myuser
----

=== Size does matter

* use alpine base image
* remove any unused downloaded archives

=== Image format

`NAMESPACE/IMAGE:TAG`
