---
version: '3'
services:
  jenkins:
    build:
      context: ./build
      args:
        # CHANGEME
        - DOCKER_HOST_DOCKER_GID=994
    image: "pomverte/jenkins:2.136-alpine"
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    logging:
      driver: "json-file"
      options:
        max-size: "10000k"
        max-file: "10"
    labels:
      org.pomverte.service: "jenkins"
      org.pomverte.maintainer: "pomverte@github.com"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  jenkins_home:
    driver: local
