# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.define "vm-vangrant-node-1" do |node1|
    node1.vm.network "private_network", ip: "192.168.99.101"
    node1.vm.provider "virtualbox" do |vb|
      vb.name = "vm-vangrant-node-1"
    end
  end

  config.vm.define "vm-vangrant-node-2" do |node2|  
    node2.vm.network "private_network", ip: "192.168.99.102"
    node2.vm.provider "virtualbox" do |vb|
      vb.name = "vm-vangrant-node-2"
    end
  end

end
